name: CI/CD Pipeline for library

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    #defaults:
    #run:
    #working-directory: root/folder

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: Print folders
        run: ls -al

      - name: setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: list files
        run: ls react-app/

      - name: install dependencies
        run: npm ci
        working-directory: react-app/

      - name: run unit tests
        run: npm run test
        working-directory: react-app/

      - name: build library
        run: npm run build
        working-directory: react-app/
